# CI/CD Pipeline for Azure DevOps Source + GitHub Actions
name: Deploy Kovaion FE to AWS EKS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'delveant_UI_testing'
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  AZURE_ORG: kovaionai
  AZURE_PROJECT: Generic-Workflows
  AZURE_REPO: kovaionai_fe

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::627133981011:role/GitHubActionsRole-Kovaion
          aws-region: ${{ env.AWS_REGION }}
          
      # Step 2: Get Azure DevOps token
      - name: Get Azure DevOps Token from Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            AZURE_DEVOPS_TOKEN,prod/azure-devops/pat
          parse-json-secrets: true
            
      # Step 3: Clone repository
      - name: Clone Repository
        env:
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          echo "Cloning kovaionai_fe from branch: $BRANCH"
          
          # Use the token (note: AWS creates AZURE_DEVOPS_TOKEN_TOKEN variable)
          git clone https://$AZURE_DEVOPS_TOKEN_TOKEN@dev.azure.com/${{ env.AZURE_ORG }}/${{ env.AZURE_PROJECT }}/_git/${{ env.AZURE_REPO }} source-code
          
          cd source-code
          git checkout $BRANCH
          
          echo "✅ Repository cloned successfully"
          ls -la
